nelmio_api_doc:
    documentation:
        info:
            title: Restaurant API
            description: Documentation de l'API Restaurant 
            version: 1.0.0
        components:
            securitySchemes:
                X-AUTH-TOKEN:
                    type: apiKey
                    name: X-AUTH-TOKEN
                    in: header
        security: 
            - X-AUTH-TOKEN: [] # Use the security scheme defined above           
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
